name = "EtherDevices"
uuid = "ff51bbf4-4a42-4211-971e-208ae71b149b"
authors = ["ChenyuBao <chenyu.bao@outlook.com>"]
version = "0.1.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
KernelAbstractions = ">=0.9.39"
Test = ">=1.11.0"
